"""empty message

Revision ID: 13a1b997572a
Revises: 24a52bb8a9ab
Create Date: 2015-09-18 10:47:57.530771

"""

# revision identifiers, used by Alembic.
revision = '13a1b997572a'
down_revision = '24a52bb8a9ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
