"""empty message

Revision ID: 1cb2b6096305
Revises: 3eab4660cd3e
Create Date: 2015-07-22 14:19:03.827482

"""

# revision identifiers, used by Alembic.
revision = '1cb2b6096305'
down_revision = '3eab4660cd3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
