"""empty message

Revision ID: 21b17e0f03a7
Revises: 450267a8af9a
Create Date: 2015-10-08 13:26:30.816598

"""

# revision identifiers, used by Alembic.
revision = '21b17e0f03a7'
down_revision = '450267a8af9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
