"""empty message

Revision ID: 24a52bb8a9ab
Revises: 5170b3337cdb
Create Date: 2015-09-18 10:47:44.191967

"""

# revision identifiers, used by Alembic.
revision = '24a52bb8a9ab'
down_revision = '5170b3337cdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GIC_CFG_GRUP',
    sa.Column('id_grup', sa.Integer(), nullable=False),
    sa.Column('nom_grup', sa.String(length=40), nullable=True),
    sa.Column('actiu', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id_grup')
    )
    op.add_column(u'GIC_CFG_PERMIS', sa.Column('grup', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'GIC_CFG_PERMIS', 'GIC_CFG_GRUP', ['grup'], ['id_grup'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'GIC_CFG_PERMIS', type_='foreignkey')
    op.drop_column(u'GIC_CFG_PERMIS', 'grup')
    op.drop_table('GIC_CFG_GRUP')
    ### end Alembic commands ###
