"""empty message

Revision ID: 283572b99607
Revises: 8ca7e120017
Create Date: 2015-07-22 11:17:38.143947

"""

# revision identifiers, used by Alembic.
revision = '283572b99607'
down_revision = '8ca7e120017'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'sexe')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('sexe', mysql.ENUM(u'0', u'1'), nullable=True))
    ### end Alembic commands ###
