"""empty message

Revision ID: 3bf4c21c78eb
Revises: 308cd12a45ef
Create Date: 2015-07-31 10:04:18.551750

"""

# revision identifiers, used by Alembic.
revision = '3bf4c21c78eb'
down_revision = '308cd12a45ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
