"""empty message

Revision ID: 3eab4660cd3e
Revises: 48506ea61736
Create Date: 2015-07-22 13:57:22.145796

"""

# revision identifiers, used by Alembic.
revision = '3eab4660cd3e'
down_revision = '48506ea61736'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
