"""empty message

Revision ID: 401b1ff1b787
Revises: 3bf4c21c78eb
Create Date: 2015-07-31 10:05:28.055367

"""

# revision identifiers, used by Alembic.
revision = '401b1ff1b787'
down_revision = '3bf4c21c78eb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GIC_ROL')
    op.drop_table('GIC_CFG_ROL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GIC_CFG_ROL',
    sa.Column('id_rol', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nom_rol', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('template', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('GIC_ROL',
    sa.Column('id_persona', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_rol', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('inici', sa.DATE(), nullable=True),
    sa.Column('fi', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], [u'post.id'], name=u'GIC_ROL_ibfk_1'),
    sa.ForeignKeyConstraint(['id_rol'], [u'GIC_CFG_ROL.id_rol'], name=u'GIC_ROL_ibfk_2'),
    sa.PrimaryKeyConstraint('id_persona', 'id_rol'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
