"""empty message

Revision ID: 450267a8af9a
Revises: 13a1b997572a
Create Date: 2015-10-08 13:25:23.567089

"""

# revision identifiers, used by Alembic.
revision = '450267a8af9a'
down_revision = '13a1b997572a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
