"""empty message

Revision ID: 4543ac4050e3
Revises: aebca7298b0
Create Date: 2015-07-28 11:04:52.516724

"""

# revision identifiers, used by Alembic.
revision = '4543ac4050e3'
down_revision = 'aebca7298b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posted')
    op.add_column('post', sa.Column('foto', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'foto')
    op.create_table('posted',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cognom1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cognom2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sexe', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('dni', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('passport', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_naix', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('telefon1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('telefon2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('actiu', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('foto', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
