"""empty message

Revision ID: 46034ab61a4
Revises: 401b1ff1b787
Create Date: 2015-07-31 10:23:01.874195

"""

# revision identifiers, used by Alembic.
revision = '46034ab61a4'
down_revision = '401b1ff1b787'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GIC_CFG_ROL',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nom_rol', sa.String(length=30), nullable=True),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('GIC_ROL',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('inici', sa.Date(), nullable=True),
    sa.Column('fi', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], [u'post.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], [u'GIC_CFG_ROL.id_rol'], ),
    sa.PrimaryKeyConstraint('id_persona', 'id_rol')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GIC_ROL')
    op.drop_table('GIC_CFG_ROL')
    ### end Alembic commands ###
