"""empty message

Revision ID: 48506ea61736
Revises: 5e9f3980eb0
Create Date: 2015-07-22 11:43:54.213604

"""

# revision identifiers, used by Alembic.
revision = '48506ea61736'
down_revision = '5e9f3980eb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
