"""empty message

Revision ID: 4df5378d1bf7
Revises: 46034ab61a4
Create Date: 2015-09-08 10:41:12.335007

"""

# revision identifiers, used by Alembic.
revision = '4df5378d1bf7'
down_revision = '46034ab61a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GIC_CFG_ROL', sa.Column('actiu', sa.String(length=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GIC_CFG_ROL', 'actiu')
    ### end Alembic commands ###
