"""empty message

Revision ID: 5170b3337cdb
Revises: f1736f828d7
Create Date: 2015-09-16 09:41:25.010874

"""

# revision identifiers, used by Alembic.
revision = '5170b3337cdb'
down_revision = 'f1736f828d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GIC_CFG_PERMIS',
    sa.Column('id_permis', sa.Integer(), nullable=False),
    sa.Column('nom_permis', sa.String(length=40), nullable=True),
    sa.Column('actiu', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id_permis')
    )
    op.create_table('GIC_PERMIS',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_permis', sa.Integer(), nullable=False),
    sa.Column('inici', sa.Date(), nullable=True),
    sa.Column('fi', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_permis'], [u'GIC_CFG_PERMIS.id_permis'], ),
    sa.ForeignKeyConstraint(['id_persona'], [u'post.id'], ),
    sa.PrimaryKeyConstraint('id_persona', 'id_permis')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GIC_PERMIS')
    op.drop_table('GIC_CFG_PERMIS')
    ### end Alembic commands ###
