"""empty message

Revision ID: 5e9f3980eb0
Revises: 283572b99607
Create Date: 2015-07-22 11:20:44.175926

"""

# revision identifiers, used by Alembic.
revision = '5e9f3980eb0'
down_revision = '283572b99607'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
