"""empty message

Revision ID: 914c53c55cc
Revises: 4f3ae7612da6
Create Date: 2015-07-29 11:25:44.915814

"""

# revision identifiers, used by Alembic.
revision = '914c53c55cc'
down_revision = '4f3ae7612da6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
