"""empty message

Revision ID: aebca7298b0
Revises: 1cb2b6096305
Create Date: 2015-07-28 11:01:19.517883

"""

# revision identifiers, used by Alembic.
revision = 'aebca7298b0'
down_revision = '1cb2b6096305'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=True),
    sa.Column('cognom1', sa.String(length=50), nullable=True),
    sa.Column('cognom2', sa.String(length=50), nullable=True),
    sa.Column('sexe', sa.String(length=1), nullable=True),
    sa.Column('dni', sa.String(length=50), nullable=True),
    sa.Column('passport', sa.String(length=50), nullable=True),
    sa.Column('data_naix', sa.String(length=50), nullable=True),
    sa.Column('telefon1', sa.String(length=50), nullable=True),
    sa.Column('telefon2', sa.String(length=50), nullable=True),
    sa.Column('email1', sa.String(length=50), nullable=True),
    sa.Column('email2', sa.String(length=50), nullable=True),
    sa.Column('actiu', sa.String(length=1), nullable=True),
    sa.Column('foto', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'post', 'foto')
    op.drop_column(u'post', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'post', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.add_column(u'post', sa.Column('foto', mysql.VARCHAR(length=50), nullable=True))
    op.drop_table('posted')
    ### end Alembic commands ###
