"""empty message

Revision ID: f1736f828d7
Revises: 4df5378d1bf7
Create Date: 2015-09-08 10:41:28.821252

"""

# revision identifiers, used by Alembic.
revision = 'f1736f828d7'
down_revision = '4df5378d1bf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
